feat: friendly naming for MO2 profiles, closes #374
Wildlander-mod/Launcher pull request #386
Opened 2021-12-15 20:55 UTC by phinocio

Implements a friendly name for the profile select drop down. Using a file named `namesMO2.json` in the MO2 `profiles` folder with the structure:

```
[
	{
		"real": "1_Wildlander-ULTRA",
		"friendly": "Ultra Quality"
	},
	{
		"real": "2_Wildlander-HIGH",
		"friendly": "High Quality"
	},
	{
		"real": "3_Wildlander-MEDIUM",
		"friendly": "Medium Quality"
	},
	{
		"real": "4_Wildlander-LOW",
		"friendly": "Low Quality"
	},
	{
		"real": "5_Wildlander-POTATO",
		"friendly": "Potato Quality"
	}
]

```

2021-12-15 21:03 UTC, MattLish requested changes

2021-12-15 21:03 UTC, MattLish commented on src/components/ProfileSelection.vue
> +    }));
We could use object destructuring to clean this up slightly

```suggestion
    this.presets = presets.map(({friendly, real}) => ({
      text: friendly,
      value: real,
    }));
```

2021-12-15 21:10 UTC, phinocio commented on src/components/ProfileSelection.vue
> +    logger.debug("Preset options are:" + this.presets);
Def true. I actually intended to remove that but forgot though haha. When it shows in the debugger it also just shows as a bunch of `[object Object]`s, which seems not useful. So I vote remove vs keep.

2021-12-15 21:12 UTC, MattLish commented on src/components/ProfileSelection.vue
> +    logger.debug("Preset options are:" + this.presets);
If it's a useful log then we can keep it. If that information isn't logged anywhere else then I think we should keep it. If it is, remove it.
If we keep it, just wrap it in JSON.stringify

```
logger.debug(`Preset options are: ${JSON.stringify(this.presets)}`);
```

2021-12-16 09:31 UTC, MattLish requested changes

2021-12-16 09:31 UTC, MattLish commented on src/main/modOrganizer.ts
> +    });
I would use a different parameter name to make it clearer.
I used `dirent` above because it was a [FileSystemEntity](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry) from passing `{ withFileTypes: true }` (so we could remove none directories).

However, after `.map((dirent) => dirent.name)` the is just an array of strings.
Always use `===` instead of `==` too.

```suggestion
    .map((preset) => ({ real: preset, friendly: preset}));
    .filter((unmappedPreset) => {
      return !mappedNames.find(
        (mappedPreset: FriendlyDirectoryMap) => mappedPreset.real === unmappedPreset
      );
    });
```

2021-12-16 09:31 UTC, MattLish commented on src/main/modOrganizer.ts
> +  return profileNames;
We can probably just combine this into a single line 

```suggestion
  return [...mappedNames, ...unmappedNames];
```

2021-12-16 09:31 UTC, MattLish commented on src/main/modOrganizer.ts
> +}
Generally speaking I think it's best to put interfaces at the top of the file. That way all interfaces are known

2021-12-16 09:31 UTC, MattLish commented on src/main/modOrganizer.ts
> +//     .filter(isNotJunk);
If this is unused, let's just remove it

```suggestion
```

2021-12-16 15:47 UTC, MattLish commented on src/components/ProfileSelection.vue
> +    logger.debug("Preset options are:" + this.presets);
I decided it's best to remove this from here, it isn't the responsibility of the view to log this really. If we want it logged it should be when we get this information.

2021-12-16 16:07 UTC, MattLish approved these changes

2021-12-16 16:09 UTC, merged