feat: create backups and copy enb files on launch
Wildlander-mod/Launcher pull request #445
Opened 2022-01-12 02:46 UTC by TaranRoth

closes #444

2022-01-12 08:09 UTC, MattLish requested changes

2022-01-12 08:09 UTC, MattLish commented on src/App.vue
> +    await startupTasks();
Does this work? I would be surprised if the render window can invoke functions like this. I think we will need an ipc event

2022-01-12 11:08 UTC, TaranRoth commented on src/App.vue
> +    await startupTasks();
It works, I can set up an ipc event if you want though.

2022-01-12 11:31 UTC, MattLish commented on src/App.vue
> +    await startupTasks();
This will perform an ENB backup every time too (because that's in the startup tasks). That could cause the backup to become corrupted because the files might have been edited.

I think we would be better tracking if the install is fresh or has been manipulated by the launcher. We can then copy ENB files if the install is fresh (like if it's been reinstalled). Otherwise, we would be copying the ENB files every time we launch which seems unnecessary for most users.
To track if it's been installed, we could just add a file to the launcher directory, if it isn't present then we know it hasn't been changed.

2022-01-12 11:39 UTC, TaranRoth commented on src/App.vue
> +    await startupTasks();
I can change it to not do the backup (maybe just invoke the copy enb files event), but I don't see how we would track if a user re-runs wabbajack.

I think as a compromise, we could 1. check if ENB files are present for the current preset 2. copy them if they aren't, do the same for both backups OR we could just modify the three functions that do backups + copy enb files to check if they have to do their task before doing it

2022-01-12 23:01 UTC, TaranRoth commented on src/App.vue
> +    await startupTasks();
Never mind, that implementation randomly stopped working, we should change it anyway I agree.

Thoughts on what I said above?

2022-01-13 09:10 UTC, MattLish commented on src/App.vue
> +    await startupTasks();
Here is what I foresee:

- User has a fresh Wildlander install. When the modpack is selected: Launcher does backup as normal, moves ENBs etc. and also creates a `launcher/_launcher-ran` file. 
- User has reinstalled Wildlander but already has a modpack location selected in launcher: launcher checks for the `launcher/_launcher-ran` file on startup which won't exist. Launcher backs up ENB files, copies ENBs etc.
- User has Wildlander already installed and `launcher/_launcher-ran` file is present: launcher does nothing on startup

So, a reinstall will copy all files on startup only for installs that haven't been manipulated by the launcher yet.

However, all that said, this is getting more and more complicated and I am being swayed to just copying ENB files on startup as you had originally. It's technically a slow process but practically it's not that slow and the whole MO2 process and starting Skyrim takes way longer, users can wait an extra 2 seconds. Perhaps we could simplify it to just:

On startup if modpack has been selected or when the modpack is selected: 
- Check if backup exists, if it doesn't then take one.
- Copy ENB files (this might replace whatever is already in there but we don't support customisation anyway).

(I realise this is basically what you said, but clarifying that it can be simplified to just that)

2022-01-14 12:07 UTC, MattLish commented
Replaced by #447

2022-01-14 12:07 UTC, closed without merging