feat(config): make more elements configurable and add static logo width
Wildlander-mod/Launcher pull request #452
Opened 2022-01-17 16:34 UTC by Guitarninja2

2022-01-18 10:11 UTC, MattLish requested changes

2022-01-18 10:11 UTC, MattLish commented on src/components/TheHeader.vue
> +  width: 265px;
Do we need a static image width? Ideally, I would like the launcher to be resizeable in the future

2022-01-18 12:37 UTC, Guitarninja2 commented on src/components/TheHeader.vue
> +  width: 265px;
It's to keep the logo from pushing elements out of the way and causing the launcher to overflow when you use a larger logo. I think the reason it works fine right now is the current Wildlander logo is the exact default size to make things not overflow or anything.

2022-01-18 14:58 UTC, Guitarninja2 commented on src/components/TheHeader.vue
> +  width: 265px;
I'm fine just making the edit on my fork though if necessary. It just may be useful for others with different sized logos.

2022-02-19 00:41 UTC, RingComics commented on src/components/TheHeader.vue
> +  width: 265px;
This repo is for the Wildlander specific launcher. You may want to check out [Azura's Star](https://github.com/RingComics/azuras-star), thats where we'll be doing the modlist agnostic launcher template ~~when I get to it~~.

Closing this PR

2022-02-19 00:41 UTC, closed without merging