feat: add api caching
Wildlander-mod/Launcher pull request #551
Opened 2022-05-30 20:51 UTC by Campiotti

closes #383 

I added a new helper directory since I didn't really see a good place to fit the CacheHelper class otherwise.
If you prefer it being in a different directory or perhaps converted to just export functions instead of a class, please open the discussions required or alternatively directly edit it yourself.

I tested this both via npm run serve and via a local build which I installed. It does seem to work as intended. To test locally  in regards to maxAge, clone it and set the maxAge to 60 or similar to do manual tests.

Initially the patreon.patrons key is twice, it seems this is due to the fact that both `TheFooter.vue` and `Patrons.vue` call `PatreonService.getPatrons`

This is my first pull request to this repo so I gladly welcome any feedback - be it regarding the code or the description here.

2022-05-31 15:43 UTC, MattLish commented
@Campiotti Thanks for the PR!

Apologies, this isn't mentioned anywhere but a lot of the backend code has changed for a 2.0.0 branch.
The best place for this to be merged into would be there.
A few changes might cause this to conflict, but if you rebase from the `chore/2.0.0` it should give a good indication of what doesn't work.
That will be merged soon to support Wildlander 1.1.

In general, a few comments:

- I try to avoid `helpers` or `util` because it starts to become a bit of a dumping ground of all sorts. I would consider this caching mechanism as another service that the Patreon and news service can call.
- Currently, there are 2 separate calls for the data I think. As part of this change, it would be nice to reduce that to just one.
- It looks like you're creating a new store instance each time which I think is unnecessary, would could keep a reference to the store instead.
- If the cache is writing to the user's filesystem, it is truly faster for those that have HDDs? Could we perhaps use something like local storage instead?

The code looks clean though :)

2022-06-01 19:10 UTC, MattLish commented
@Campiotti  A lot changed in the backend in 2.0.0. One of the biggest changes was the renderer process no longer has access to any node APIs except when communicating via ipc handlers (our controllers). 
If we want to persist something, I would suggest doing it in a service in the main process and having a controller expose an ipc handler.
I would also recommend if we want to use electron store that we use a different store with a different name, so it doesn't end up in the user preferences. Perhaps we can just call it `cache.json` or something

2022-06-03 19:41 UTC, Campiotti commented
Same as #552 , rebased onto 2.0.0 & target branch changed.

Manually tested.

2022-06-18 07:53 UTC, Campiotti commented
@MattLish is this (as well as #552 #556 ) still expected to be merged into 2.0.0?

If so, should I start resolving conflicts or what's the plan here?

2022-06-18 12:18 UTC, MattLish commented
Hey @Campiotti , I haven't forgotten about these! :)
I've just had a lot to do before Wildlander 1.1 comes out. 2.0.0 of the launcher will get released soon and we can merge these just after that. Each merge to master produces a release anyway, so it's not like it'll have to wait for the next big release.
I'll endeavour to get these merged next week :)

As for the conflicts, this is just because I had to rebase the chore/2.0.0 branch a few times to get the commits in a good releasable state.
If you cherry-pick your commit (or rebase onto an updated origin/2.0.0) you should have no conflicts.
I can sort this next week when I come to merge them though :)

2022-06-18 12:18 UTC, MattLish requested changes

2022-06-19 11:42 UTC, Campiotti commented on src/renderer/services/patreon.service.ts
> +    const data = this.cacheService.get<Patron[]>(this.cacheKey, 60 * 60 * 24);
Adjusted this in [fc8a271](https://github.com/Wildlander-mod/Launcher/pull/551/commits/fc8a2719a682130371d54b265a3be9bf1cabe120)

2022-06-19 11:42 UTC, Campiotti commented on src/renderer/services/patreon.service.ts
> +    const data = this.cacheService.get<Patron[]>(this.cacheKey, 60 * 60 * 24);
[fc8a271](https://github.com/Wildlander-mod/Launcher/pull/551/commits/fc8a2719a682130371d54b265a3be9bf1cabe120)

2022-06-19 11:43 UTC, Campiotti commented on src/renderer/services/patreon.service.ts
> +  private cacheService = new CacheService();
Adjusted in [fc8a271](https://github.com/Wildlander-mod/Launcher/pull/551/commits/fc8a2719a682130371d54b265a3be9bf1cabe120)

2022-06-19 13:18 UTC, closed without merging